rootProject.name = 'minigenesys-backend'

include 'shared-common'
include 'api-gateway'
include 'call-service'
include 'telephony-service'
include 'agent-state-service'
include 'routing-service'
include 'analytics-service'
include 'websocket-gateway'
include 'freeswitch-service'
include 'audit-service'
include 'user-service'
